WITH CITY_COUNT AS (
  SELECT CITY, COUNT(*) AS FACILITY_COUNT
  FROM RAW_DATA.SALES_DATA
  GROUP BY CITY
  HAVING FACILITY_COUNT > 3
),
FILTERED_FACILITIES AS (
  SELECT f.FACILITY_ID, f.COUNTRY, f.API_SOLD_PRODUCT, 
         f.SOLD_PRODUCT_CREATED_AT, f.QUANTITY_SOLD, f.UNIT_PRICE
  FROM RAW_DATA.SALES_DATA f
  INNER JOIN CITY_COUNT c ON f.CITY = c.CITY
),
SALES_BY_PRODUCT_COUNTRY AS (
  SELECT COUNTRY, API_SOLD_PRODUCT AS PRODUCT_NAME, 
         SUM(QUANTITY_SOLD) AS TOTAL_SOLD,
         AVG(UNIT_PRICE) AS AVERAGE_PRICE,
         MIN(SOLD_PRODUCT_CREATED_AT) AS FIRST_SALE,
         MAX(SOLD_PRODUCT_CREATED_AT) AS MOST_RECENT_SALE
  FROM FILTERED_FACILITIES
  WHERE SOLD_PRODUCT_CREATED_AT >= DATEADD(YEAR, -1, CURRENT_DATE())
  GROUP BY COUNTRY, API_SOLD_PRODUCT
)
SELECT *
FROM SALES_BY_PRODUCT_COUNTRY;